# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Major Ursa"
description: > # this means to ignore newlines until "baseurl:"
  Major Ursa Integalactic Blogging Service
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://majorursa.github.io" # the base hostname & protocol for your site
github_username:  majorursa

# Build settings
markdown: kramdown

# oh the collections
collections:
- notes
- cats
- paintings
- catgifs


